# re-enable a specific script via `package.json:dependenciesMeta:<moduleName>:built = true`
enableScripts: false

compressionLevel: mixed
enableGlobalCache: false
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.12.0.cjs
