FROM node:18-alpine
RUN apk add --no-cache bash
RUN apk add --no-cache postgresql-client

ENTRYPOINT ["yarn"]
CMD ["watch"]

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile && yarn cache clean

COPY ./__tests__ ./__tests__
COPY ./sql ./sql
COPY ./src  ./src
COPY ./scripts ./scripts
COPY ./perfTest  ./perfTest
COPY ./website  ./website
COPY ./tsconfig.json ./
COPY ./jest.config.js ./
COPY ./.eslintrc.js ./
COPY ./.prettierrc.js ./
COPY ./.eslintignore ./

RUN yarn prepack
