#!/usr/bin/env bash
set -e

dropdb --if-exists graphile_worker_dump
dropuser graphile_worker_role || true
psql template1 -c "CREATE USER graphile_worker_role WITH SUPERUSER PASSWORD 'password';"
createdb graphile_worker_dump -O graphile_worker_role
PGPASSWORD=password psql -X -U graphile_worker_role -v ON_ERROR_STOP=1 -f scripts/ensure_gen_random_uuid_exists.sql graphile_worker_dump
PGUSER=graphile_worker_role PGPASSWORD=password PGHOST=localhost ts-node src/cli.ts -c graphile_worker_dump --schema-only
pg_dump --schema-only --no-owner graphile_worker_dump | sed -e '/^--/d' -e '/^\s*$/d' -e '/^SET /d' -e 's/EXECUTE FUNCTION/EXECUTE PROCEDURE/g' > __tests__/schema.sql
dropdb graphile_worker_dump
dropuser graphile_worker_role
