# re-enable a specific script via `package.json:dependenciesMeta:<moduleName>:built = true`
enableScripts: false

# Don't install anything that was released less than a week ago
npmMinimalAgeGate: "1w"
# Unless it's one of ours:
npmPreapprovedPackages:
  - "jest-time-helpers"
  - "graphile"
  - "graphile-config"
  - "@graphile/*"

approvedGitRepositories:
  - "https://github.com/yarnpkg/*"
  - "ssh://git@github.com/yarnpkg/*"

# ------------------------------------------------------------------------------

compressionLevel: mixed
enableGlobalCache: false
nodeLinker: node-modules

yarnPath: ../.yarn/releases/yarn-4.16.0.cjs
